version: '3'

services:

  db:
    ports:
      - 5432:5432
    env_file:
      - ./envs/dev_database.env

  # alembic:
  #   image: raspisden-python:latest
  #   command: tail -f /dev/null
  #   volumes:
  #     - ./apps/alembic.ini:/usr/src/app/alembic.ini
  #     - ./apps/alembic:/usr/src/app/alembic
  #     - ./apps/database:/usr/src/app/database
  #     - ./apps/conftest.py:/usr/src/app/conftest.py
  #   depends_on:
  #     - db
  #   env_file:
  #     - ./envs/dev_beat.env
  #     - ./envs/dev_database.env
  #     - ./envs/dev_telegram.env
  #     - ./envs/dev_worker.env
  #     - ./envs/dev_database_exporter.env
  
  nginx:
    volumes:
      - ./nginx_dev.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
      - public
